const { Schema, default:mongoose} = require('mongoose')

const orderSchema = new Schema({
    products: [
    {
        product: {
            type: Schema.Types.ObjectId,
            ref: 'Product'
        },
        count: {
            type: Number
        },
    }
    ],
    totalPrice: {
      type: Number,
      required: true
    },
    paymentIntent: {
        type: String,
        required: true
    },
    orderStatus: {
        type: String, 
        default: "Order Placed",
        enum: ["Order Placed", "Processing", "Dispatched", "Delivered", "Cancelled"]
    },
    orderby: {
        type: Schema.Types.ObjectId,
        ref: 'User',
        required: true
    }
    },
    {
        timestamps: true
    }
)

orderSchema.virtual('createdAtFormatted').get(function () {
    // `this.createdAt` is the Date object generated by Mongoose
    const months = ['January', 'February', 'March', 'April', 'May', 'June', 'July',
      'August', 'September', 'October', 'November', 'December'];
    
    const date = this.createdAt.getDate().toString().padStart(2, '0');
    const month = months[this.createdAt.getMonth()];
    const year = this.createdAt.getFullYear();
    
    return `${date} ${month} ${year}`; // Return DD Month YYYY format
  });

const Order = mongoose.model('Order', orderSchema)
module.exports = Order
